version: 2.1

jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk-stretch
    steps:
      - checkout
      - run: mvn dependency:go-offline
      - save_cache:
          paths:
            - ~/.m2
          key: build-{{ checksum "pom.xml" }}
      - run: mvn package
      - store_test_results:
          path: target/reports
      - store_artifacts:
          path: target/artifacts
          destination: Jibiki.jar

  deploy:
    machine:
      enabled: true
    steps:
      - run:
          name: Deploy Jibiki
          command: |
            scp target/artifacts/Jibiki.jar $SSH_USER@$SSH_HOST:~/Jibiki.jar
            ssh $SSH_USER@$SSH_HOST "sudo systemctl restart Jibiki"

workflows:
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master