version: 2.1

jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk-stretch

    steps:
      - checkout
      - run: mvn dependency:go-offline
      - save_cache:
          paths:
            - ~/.m2
          key: build-{{ checksum "pom.xml" }}
      - run: mvn package
      - store_test_results:
          path: target/reports